# Generated by Django 4.2 on 2023-05-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('titleEn', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='عنوان')),
                ('metaTitle', models.CharField(max_length=120)),
                ('metaKeywords', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('pageSizeOptions', models.CharField(max_length=120)),
                ('displayOrder', models.IntegerField(null=True)),
                ('pageSize', models.IntegerField()),
                ('metaDescription', models.CharField(max_length=120)),
                ('isPublished', models.BooleanField(default=True, verbose_name='منتشر شده / منتشر نشده')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('allowCustomersToSelectPageSize', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('isDelete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('titleEn', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='عنوان')),
                ('metaTitle', models.CharField(max_length=120)),
                ('metaKeywords', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('pageSizeOptions', models.CharField(max_length=120)),
                ('displayOrder', models.IntegerField()),
                ('pageSize', models.IntegerField()),
                ('metaDescription', models.CharField(max_length=120)),
                ('fullName', models.CharField(max_length=120)),
                ('isPublished', models.BooleanField(default=True, verbose_name='منتشر شده / منتشر نشده')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('allowCustomersToSelectPageSize', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('showOnHomepage', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('includeInTopMenu', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('subjectToAcl', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('limitedToStores', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('isDelete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=120)),
                ('createdByBrowserName', models.CharField(max_length=120)),
                ('createdByIp', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sendAlarm', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('type', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('nameEn', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='عنوان')),
                ('metaTitle', models.CharField(max_length=120)),
                ('metaKeywords', models.CharField(max_length=120)),
                ('shortDescription', models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات اصلی')),
                ('metaDescription', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('isUsed', models.BooleanField(verbose_name='کارکرده')),
                ('showOnHomepage', models.BooleanField(default=True, verbose_name='نمایش در صفحه اصلی / عدم نمایش در صفحه اصلی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('isDelete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('link', models.CharField(max_length=255)),
                ('inStock', models.BooleanField(default=True)),
                ('recordedAt', models.DateField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productItem_product', to='product.product')),
            ],
        ),
    ]
