# Generated by Django 4.2 on 2023-05-19 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor', '0001_initial'),
        ('product', '0001_initial'),
        ('upload', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='vendorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productItem_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='brandId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='کتگوری'),
        ),
        migrations.AddField(
            model_name='product',
            name='pictureGallery',
            field=models.ManyToManyField(related_name='product_pictureGallery', to='upload.upload', verbose_name='عکس ها'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceHistory_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='like',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='like',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteProduct_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.comment', verbose_name='کامنت والد'),
        ),
        migrations.AddField(
            model_name='comment',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='product.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_parent', to='product.category', verbose_name='دسته بندی والد'),
        ),
        migrations.AddField(
            model_name='category',
            name='pictureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_picture', to='upload.upload', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='brand',
            name='iconId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_icon', to='upload.upload', verbose_name='ایکون'),
        ),
        migrations.AddField(
            model_name='brand',
            name='pictureId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_picture', to='upload.upload', verbose_name='عکس'),
        ),
    ]
