# Generated by Django 4.2 on 2023-05-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_brand_allowcustomerstoselectpagesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='published', max_length=255),
        ),
    ]
