# Generated by Django 4.2 on 2023-05-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isUsed',
            field=models.BooleanField(default=False, verbose_name='کارکرده'),
        ),
    ]
