# Generated by Django 4.2 on 2023-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='recordedAt',
            field=models.DateTimeField(),
        ),
    ]
