# Generated by Django 4.2 on 2023-06-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='internal',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='برند داخلی / برند خارجی'),
        ),
    ]
