# Generated by Django 4.2 on 2023-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(blank=True, db_index=True, max_length=200, unique=True),
        ),
    ]
